package gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T14:01:48.229+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RgWsBasStoixN", 
                  wsdlLocation = "https://www1.gsis.gr/wsgsis/RgWsBasStoixN/RgWsBasStoixNSoapHttpPort?wsdl",
                  targetNamespace = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl") 
public class RgWsBasStoixN_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", "RgWsBasStoixN");
    public final static QName RgWsBasStoixNSoapHttpPort = new QName("http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", "RgWsBasStoixNSoapHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("https://www1.gsis.gr/wsgsis/RgWsBasStoixN/RgWsBasStoixNSoapHttpPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RgWsBasStoixN_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://www1.gsis.gr/wsgsis/RgWsBasStoixN/RgWsBasStoixNSoapHttpPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RgWsBasStoixN_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RgWsBasStoixN_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RgWsBasStoixN_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RgWsBasStoixN
     */
    @WebEndpoint(name = "RgWsBasStoixNSoapHttpPort")
    public RgWsBasStoixN getRgWsBasStoixNSoapHttpPort() {
        return super.getPort(RgWsBasStoixNSoapHttpPort, RgWsBasStoixN.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RgWsBasStoixN
     */
    @WebEndpoint(name = "RgWsBasStoixNSoapHttpPort")
    public RgWsBasStoixN getRgWsBasStoixNSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(RgWsBasStoixNSoapHttpPort, RgWsBasStoixN.class, features);
    }

}
