
package gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T14:01:48.141+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class RgWsBasStoixN_RgWsBasStoixNSoapHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", "RgWsBasStoixN");

    private RgWsBasStoixN_RgWsBasStoixNSoapHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RgWsBasStoixN_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RgWsBasStoixN_Service ss = new RgWsBasStoixN_Service(wsdlURL, SERVICE_NAME);
        RgWsBasStoixN port = ss.getRgWsBasStoixNSoapHttpPort();  
        
        {
        System.out.println("Invoking rgWsBasStoixN...");
        java.lang.String _rgWsBasStoixN_pAfm = "_rgWsBasStoixN_pAfm-1712589950";
        gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser _rgWsBasStoixN_pBasStoixNRecOutVal = new gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser();
        _rgWsBasStoixN_pBasStoixNRecOutVal.setActLongDescr("ActLongDescr-66297150");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setPostalZipCode("PostalZipCode628774445");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setFacActivity(new java.math.BigDecimal("-1866092372973276230.2228951200821763003"));
        _rgWsBasStoixN_pBasStoixNRecOutVal.setRegistDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2011-11-14T14:01:48.194+02:00"));
        _rgWsBasStoixN_pBasStoixNRecOutVal.setStopDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2011-11-14T14:01:48.195+02:00"));
        _rgWsBasStoixN_pBasStoixNRecOutVal.setDoyDescr("DoyDescr2122455047");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setParDescription("ParDescription-1263786638");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setDeactivationFlag("DeactivationFlag-1535355710");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setPostalAddressNo("PostalAddressNo2113378541");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setPostalAddress("PostalAddress-56247463");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setDoy("Doy68955498");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setFirmPhone("FirmPhone294151241");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setOnomasia("Onomasia-1142357873");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setFirmFax("FirmFax822895801");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setAfm("Afm-1974390157");
        _rgWsBasStoixN_pBasStoixNRecOutVal.setCommerTitle("CommerTitle-1634685983");
        javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser> _rgWsBasStoixN_pBasStoixNRecOut = new javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser>(_rgWsBasStoixN_pBasStoixNRecOutVal);
        java.math.BigDecimal _rgWsBasStoixN_pCallSeqIdOutVal = new java.math.BigDecimal("2092686796565491695.3756569804341209726");
        javax.xml.ws.Holder<java.math.BigDecimal> _rgWsBasStoixN_pCallSeqIdOut = new javax.xml.ws.Holder<java.math.BigDecimal>(_rgWsBasStoixN_pCallSeqIdOutVal);
        gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser _rgWsBasStoixN_pErrorRecOutVal = new gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser();
        _rgWsBasStoixN_pErrorRecOutVal.setErrorDescr("ErrorDescr551241168");
        _rgWsBasStoixN_pErrorRecOutVal.setErrorCode("ErrorCode-739739681");
        javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser> _rgWsBasStoixN_pErrorRecOut = new javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser>(_rgWsBasStoixN_pErrorRecOutVal);
        port.rgWsBasStoixN(_rgWsBasStoixN_pAfm, _rgWsBasStoixN_pBasStoixNRecOut, _rgWsBasStoixN_pCallSeqIdOut, _rgWsBasStoixN_pErrorRecOut);

        System.out.println("rgWsBasStoixN._rgWsBasStoixN_pBasStoixNRecOut=" + _rgWsBasStoixN_pBasStoixNRecOut.value);
        System.out.println("rgWsBasStoixN._rgWsBasStoixN_pCallSeqIdOut=" + _rgWsBasStoixN_pCallSeqIdOut.value);
        System.out.println("rgWsBasStoixN._rgWsBasStoixN_pErrorRecOut=" + _rgWsBasStoixN_pErrorRecOut.value);

        }
        {
        System.out.println("Invoking rgWsBasStoixNVersionInfo...");
        java.lang.String _rgWsBasStoixNVersionInfo__return = port.rgWsBasStoixNVersionInfo();
        System.out.println("rgWsBasStoixNVersionInfo.result=" + _rgWsBasStoixNVersionInfo__return);


        }

        System.exit(0);
    }

}
