
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T14:01:48.204+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "RgWsBasStoixN",
                      portName = "RgWsBasStoixNSoapHttpPort",
                      targetNamespace = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl",
                      wsdlLocation = "https://www1.gsis.gr/wsgsis/RgWsBasStoixN/RgWsBasStoixNSoapHttpPort?wsdl",
                      endpointInterface = "gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl.RgWsBasStoixN")
                      
public class RgWsBasStoixNImpl implements RgWsBasStoixN {

    private static final Logger LOG = Logger.getLogger(RgWsBasStoixNImpl.class.getName());

    /* (non-Javadoc)
     * @see gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl.RgWsBasStoixN#rgWsBasStoixN(java.lang.String  pAfm ,)gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser  pBasStoixNRecOut ,)java.math.BigDecimal  pCallSeqIdOut ,)gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser  pErrorRecOut )*
     */
    public void rgWsBasStoixN(java.lang.String pAfm,javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser> pBasStoixNRecOut,javax.xml.ws.Holder<java.math.BigDecimal> pCallSeqIdOut,javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser> pErrorRecOut) { 
        LOG.info("Executing operation rgWsBasStoixN");
        System.out.println(pAfm);
        System.out.println(pBasStoixNRecOut.value);
        System.out.println(pCallSeqIdOut.value);
        System.out.println(pErrorRecOut.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl.RgWsBasStoixN#rgWsBasStoixNVersionInfo(*
     */
    public java.lang.String rgWsBasStoixNVersionInfo() { 
        LOG.info("Executing operation rgWsBasStoixNVersionInfo");
        try {
            java.lang.String _return = "_return1615121650";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
