package gr.gsis.rgwsbasstoixn.rgwsbasstoixn.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-11-14T14:01:48.219+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", name = "RgWsBasStoixN")
@XmlSeeAlso({gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RgWsBasStoixN {

    @WebMethod(action = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixN")
    public void rgWsBasStoixN(
        @WebParam(partName = "pAfm", name = "pAfm")
        java.lang.String pAfm,
        @WebParam(partName = "pBasStoixNRec_out", mode = WebParam.Mode.INOUT, name = "pBasStoixNRec_out")
        javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.RgWsBasStoixNRtUser> pBasStoixNRecOut,
        @WebParam(partName = "pCallSeqId_out", mode = WebParam.Mode.INOUT, name = "pCallSeqId_out")
        javax.xml.ws.Holder<java.math.BigDecimal> pCallSeqIdOut,
        @WebParam(partName = "pErrorRec_out", mode = WebParam.Mode.INOUT, name = "pErrorRec_out")
        javax.xml.ws.Holder<gr.gsis.rgwsbasstoixn.rgwsbasstoixn_wsdl.types.GenWsErrorRtUser> pErrorRecOut
    );

    @WebResult(name = "result", targetNamespace = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", partName = "result")
    @WebMethod(action = "http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixNVersionInfo")
    public java.lang.String rgWsBasStoixNVersionInfo();
}
